# version: '3.8'
# services:
#   # app:
#   #   build: .
#   #   command: npm start
#   #   depends_on:
#   #     - db
#   #   environment:
#   #     DATABASE_URL: postgres://postgres:postgres@db:5432/db
#   #     NODE_ENV: development
#   #     PORT: 3001
#   #   ports:
#   #     - "3001:3001"